### ISSUE TITLE
Question about "Focusing strength" of APL

### ISSUE THREAD

**Issue by zhangli28** [AngelFP/Wake-T#136]
Dear All,

I have a question about calculation of the "focusing strength" of an Active Plasma Lens (APL). 

We give directly the value of the focusing strength of the APL in the code. In general, for APL, in my understanding, it should depend on at least two parameters:

(1) Plasma density and its length in the APL, and
(2) Applied voltage or current.

Both these should contribute to the net azimuthal magnetic field. Flow of current depends on the movement of the plasma electrons towards the electrodes (if we consider capillary discharge). 

Could you please, help me to understand if we fix the length of APL and plasma density inside the APL then how to determine the focusing strength.  

When I follow the reference PRL, 115, 184802 (2015), the focusing strength only depends on the current and radius, but no plasma density dependence. 

Thanks a lot.

**Comment by jonasbjorklundsvensson** [comment]
Hi @zhangli28 ,

For an APL in its nominal operating mode, the focusing gradient depends only on the current density, i.e. the current and the radius for a round capillary. 

Wakes are generally detrimental to operation in this mode. For single bunches, wakes often cause varying focusing along the bunch caused by the magnetic and electric wakefields, at least to some extent. However, exactly how this behaves is a complex question that depends on the bunch parameters and the plasma - you can check https://arxiv.org/abs/1802.02750 for a theoretical treatment of this exact case.

For pure focusing with wakefields, one normally tries to be in the blowout regime where the focusing fields are linear and constant along the focused bunch. This generally requires a driver-witness pair, and is then referred to as a passive plasma lens (PPL). 

Hope this clears up the confusion!
/ Jonas

**Comment by zhangli28** [comment]
Hi @jonasbjorklundsvensson ,

Thank you for the explanation. I agree with your point. Also, after reading some papers on APL / PPL, I hope now I understand it relatively better than before.

If I follow the literature as given in the papers, then these imply that for APL, one must consider the measured current value from the experiment (or take reference value from the experimental data available from published papers) and then calculate the focusing strength as described in https://arxiv.org/abs/1802.02750 or  PRL, 115, 184802 (2015).  Please, tell me if I am wrong ?

**Comment by AngelFP** [comment]
Hi @zhangli28,

As @jonasbjorklundsvensson says, the focusing gradient in an APL depends on the current and the radius of the capillary. But this is modeled differently in Wake-T.

In Wake-T you give directly the value of the focusing strength. When `wakefields=False`, everything that Wake-T does is track the beam evolution through a linear azimuthal magnetic field with the given strength. There is actually no plasma. The plasma is only included then `wakefields=True`, so that the wake generated by the beam (if the beam is intense enough) can be modeled, as it can lead to additional focusing. However, the two fields are decoupled: the linear azimuthal field is externally applied, and does not arise from current flowing in the plasma. This is an approximation, and it is why you do not need specify the radius and the current.

If you want to compute the field from a current and radius, you can use Eq (1) in your reference and then give the resulting value to Wake-T.

**Comment by zhangli28** [comment]
Hi @AngelFP , 

Thank you for the clear explanation. Now, I can use the APL utility without any confusion. 

Just last query,  does space charge effect is also considered during beam transportation (Drift etc.) ?

Thanks to both of you ( @AngelFP , @jonasbjorklundsvensson ).

**Comment by AngelFP** [comment]
Glad to hear :)

There is currently no space-charge in the beam transport elements, only in the plasma elements when the wakefields are enabled,

**Comment by zhangli28** [comment]
HI @AngelFP ,

Thank you for always helping and clearing the doubts. I hope in future space-charge effect will also be included in the beam transportation line. 

Thank you.
